name: todo_test
description: Rocketlab Test.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Animation
  cupertino_icons: ^1.0.2

  # Architecture
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1

  # Persistence and Local Storage
  shared_preferences: ^2.0.15

  # API, JSON and Models
  freezed_annotation: ^2.1.0
  json_serializable: ^6.4.0
  sqflite: ^2.1.0

  # Testing and Development
  bloc_test: ^9.1.0

  # Utils
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  analyzer: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  freezed: ^2.1.0
  injectable_generator: ^1.5.4
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  sqflite_common_ffi: ^2.1.1+1

flutter:
  uses-material-design: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
